/**
 * @file db/schemas/tasks/scheduled_tasks.ts
 * @description Drizzle schema for the `scheduled_tasks` table.
 *
 * A `scheduledTask` row is the saved DEFINITION of a recurring/one-shot/on-demand
 * agent action created by the Tasks scheduling wizard. It captures the chosen
 * agent surface, the catalog action, its parameters, the target account(s), a
 * frequency (on_demand | once | interval | cron), an optional natural-language
 * prompt to run over the action result, and optional indexing flags (D1 + RAG).
 *
 * This is DISTINCT from the `tasks` table, which records individual RUN instances
 * (one per fire) with their live `task_events` progress feed.
 */

import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

/**
 * Saved scheduled-task definitions backing the `/tasks` scheduling wizard.
 */
export const scheduledTasks = sqliteTable("scheduled_tasks", {
  /** UUID primary key generated by the runtime. */
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  /** Human-readable task title shown in the UI list. */
  title: text("title").notNull(),
  /** JSON array of target account selectors (emails or "workspace"/"personal"). */
  accountsJson: text("accounts_json", { mode: "json" })
    .$type<string[]>()
    .notNull(),
  /** Which specialist agent surface executes the action. */
  agent: text("agent", {
    enum: ["gmail", "docs", "sheets", "slides", "drive", "appscript", "calendar"],
  }).notNull(),
  /** Catalog action name (e.g. "listLabels", "createDocument"). */
  action: text("action").notNull(),
  /** JSON object of action parameters keyed by ParamDef.name. */
  paramsJson: text("params_json", { mode: "json" })
    .$type<Record<string, unknown>>()
    .notNull(),
  /** Optional natural-language instruction run by the LLM over the action result. */
  promptText: text("prompt_text"),
  /** How often the task fires. */
  frequency: text("frequency", {
    enum: ["on_demand", "once", "interval", "cron"],
  }).notNull(),
  /** Frequency spec: ISO datetime (once) | seconds (interval) | cron expression. */
  scheduleSpec: text("schedule_spec"),
  /** JSON array of per-account agent schedule ids returned by the Agents SDK. */
  scheduleIdsJson: text("schedule_ids_json", { mode: "json" }).$type<string[]>(),
  /** Whether to store raw run results in D1. */
  indexToD1: integer("index_to_d1", { mode: "boolean" }).notNull().default(false),
  /** Which RAG corpus (if any) to embed run results into. */
  indexVectorizeCorpus: text("index_vectorize_corpus", {
    enum: ["emails", "docs", "general"],
  }),
  /** Lifecycle state of the definition. */
  status: text("status", {
    enum: ["active", "paused", "completed", "error"],
  })
    .notNull()
    .default("active"),
  /** How the definition was created. */
  source: text("source", {
    enum: ["ui", "mcp", "api", "rpc"],
  })
    .notNull()
    .default("ui"),
  /** Unix-epoch timestamp of the most recent run. */
  lastRunAt: integer("last_run_at", { mode: "timestamp" }),
  /** Unix-epoch timestamp of the next scheduled run, when known. */
  nextRunAt: integer("next_run_at", { mode: "timestamp" }),
  /** Unix-epoch timestamp when the definition was created. */
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  /** Unix-epoch timestamp of the last update. */
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
});

/** Zod schema for selecting rows from `scheduled_tasks`. */
export const selectScheduledTaskSchema = createSelectSchema(scheduledTasks);
/** Zod schema for inserting rows into `scheduled_tasks`. */
export const insertScheduledTaskSchema = createInsertSchema(scheduledTasks);
