/**
 * @file db/schemas/agents/tasks.ts
 * @description Drizzle schema for the `agent_tasks` table.
 * A task represents a unit of work dispatched to a specialist agent
 * (docs, sheets, slides, drive, gmail, appscript, or chat).
 * Tasks are observable in the UI and may be triggered from the UI,
 * MCP tools, direct API calls, or inter-agent RPC.
 *
 * Ported from `core-gsuite-tools` `db/schemas/tasks/tasks.ts`. Renamed
 * table/export (`tasks` -> `agentTasks`, SQL table `tasks` -> `agent_tasks`)
 * because this worker already has an unrelated `tasks` table (project-management
 * domain, see `../tasks/tasks.ts`) that would otherwise collide on both the D1
 * table name and the exported symbol.
 */

import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

/**
 * Central agent-task registry.  Every agent action that produces a Google
 * artifact or a significant async operation writes a row here so the UI can
 * poll it.
 */
export const agentTasks = sqliteTable("agent_tasks", {
  /** UUID primary key generated by the runtime. */
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  /**
   * Which Google surface (or chat) this task operates on.
   * Matches the specialist agent names.
   */
  kind: text("kind", {
    enum: ["docs", "sheets", "slides", "drive", "gmail", "appscript", "chat"],
  }).notNull(),
  /** Human-readable task title shown in the UI. */
  title: text("title").notNull(),
  /** Lifecycle state of the task. */
  status: text("status", {
    enum: ["pending", "running", "done", "error"],
  })
    .notNull()
    .default("pending"),
  /** Google account context that will execute the task: "workspace" | "personal". */
  account: text("account").notNull(),
  /** Durable Object agent name responsible for executing this task. */
  agent: text("agent").notNull(),
  /** Session that initiated the task, if applicable. */
  sessionId: text("session_id"),
  /** Chat thread tied to this task, if applicable. */
  threadId: text("thread_id"),
  /** Google file id of the primary artifact (doc, sheet, etc.), if any. */
  googleFileId: text("google_file_id"),
  /** Google file URL of the primary artifact, used for the iframe preview. */
  googleFileUrl: text("google_file_url"),
  /** How the task was triggered. */
  source: text("source", {
    enum: ["ui", "mcp", "api", "rpc"],
  }).notNull(),
  /** Unix-epoch timestamp when the task was created. */
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  /** Unix-epoch timestamp of the last status update. */
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  /** Arbitrary JSON metadata (tool args, extra context, error details). */
  metadataJson: text("metadata_json", { mode: "json" }),
});

/** Zod schema for selecting rows from `agent_tasks`. */
export const selectAgentTaskSchema = createSelectSchema(agentTasks);
/** Zod schema for inserting rows into `agent_tasks`. */
export const insertAgentTaskSchema = createInsertSchema(agentTasks);
