/**
 * @file db/schemas/tasks/task_events.ts
 * @description Drizzle schema for the `task_events` table.
 * Append-only live progress feed for tasks.  Each row is a discrete
 * event emitted by an agent during task execution (start, progress,
 * tool call, completion, error).  The UI polls or streams these rows
 * to render real-time task progress.
 */

import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

/**
 * Append-only event log for task progress.
 * Rows are never updated — only inserted.
 * Consumers should order by `ts ASC` to reconstruct the event timeline.
 */
export const taskEvents = sqliteTable("task_events", {
  /** UUID primary key generated by the runtime. */
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  /** Foreign key to the parent `tasks` row. */
  taskId: text("task_id").notNull(),
  /** Unix-epoch timestamp of when the event occurred. */
  ts: integer("ts", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  /** Short event type label (e.g. "start", "tool_call", "progress", "done", "error"). */
  type: text("type").notNull(),
  /** Human-readable event message for display in the UI. */
  message: text("message").notNull(),
  /** Optional JSON payload with structured event data (tool args, partial results, etc.). */
  dataJson: text("data_json", { mode: "json" }),
});

/** Zod schema for selecting rows from `task_events`. */
export const selectTaskEventSchema = createSelectSchema(taskEvents);
/** Zod schema for inserting rows into `task_events`. */
export const insertTaskEventSchema = createInsertSchema(taskEvents);
